# Use a imagem oficial do PHP com FPM
FROM php:8.3.0-fpm

# Instale as dependências necessárias
RUN apt-get update && apt-get install -y git curl zip vim unzip libpq-dev

# Instale as extensões PHP necessárias
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable pdo_mysql

# Defina o diretório de trabalho para o Nginx
WORKDIR /var/www