version: '3'

networks:
  nginx-php8-mysql_8:

services:

  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: campeonato_app
    restart: always
    working_dir: /var/www
    volumes:
     - ../src:/var/www
    networks:
     - nginx-php8-mysql_8

  nginx:
    image: nginx:1.24.0-alpine-slim
    container_name: campeonato_nginx
    restart: always
    depends_on:
      - mysql_8
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
     - nginx-php8-mysql_8
    
  mysql_8:
    image: mysql:latest
    container_name: campeonato_db
    restart: always
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: campeonato
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev_nikollas
      MYSQL_PASSWORD: nikollas
      MYSQL_HOST: "*"
    volumes:
      - ./mysql:/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    networks:
     - nginx-php8-mysql_8